### ISSUE TITLE
ValidInputTypes is not enough, like type="number"

### ISSUE THREAD

**Issue by xialvjun** [slorber/backspace-disabler#1]
var ValidInputTypes = ['TEXT','PASSWORD','FILE','EMAIL','SEARCH','DATE'];

..........

**Comment by slorber** [comment]
@xialvjun can you make an exhaustive list of what's missing? Also don't hesitate to submit a PR

**Comment by slorber** [comment]
Would it be ok if I add these ones?:

number / month / week / time / datetime / datetime-local / tel / url

**Comment by slorber** [comment]
released as 1.1.0
