### ISSUE TITLE
ConnectedToTheDOM Regression

### ISSUE THREAD

**Issue by ahutchings** [slorber/backspace-disabler#5]
I have a bit of a strange use case that no longer works after #4 went in.

In my application, I have a parent window that spawns secondary windows. The parent window then disables these secondary windows by passing the secondary window references to BackspaceDisabler.disable(secondaryWindow). The issue is that when I hit backspace in a form element (or content-editable) in the secondary window, the event is prevented. This is because the document that is found by traversing `node.parentNode` in `connectedToTheDom` (the secondary window's document) is a different reference than the global document (the primary window's document).

One potential fix is to check the `nodeType` of the node instead of checking the reference against the `document` global. If `node.nodeType === Node.DOCUMENT_NODE`, we've found the closest parent document.

If this seems acceptable then I can submit a pull request for it.

cc @fresheneesz

**Comment by fresheneesz** [comment]
Seems like a reasonable thing to do to me.

**Comment by slorber** [comment]
Not sure to understand your usecase, you mean your app open other tabs or iframes? 

I'm not sure how you do to pass references from one window to another, isn't the only communication channel through postMessage, requiring elements to be serialized?

`node.nodeType === Node.DOCUMENT_NODE` does not seem harmful for other usecases so if it works for you why not.

**Comment by ahutchings** [comment]
The main window is spawning new windows using window.open. The secondary windows are same-origin as the primary, so they have full access to globals defined in other windows and can pass references.

I will submit a pull request for this shortly.
